version: '3.4'

services:
  agl_microservices:
    image: ${ACR_LOGINSERVER-}aglmicroservices
    build:
      context: .
      dockerfile: AGL_Microservices\Dockerfile

  authenticationservices:
    image: ${ACR_LOGINSERVER-}authenticationservices
    build:
      context: .
      dockerfile: AuthenticationServices\Dockerfile


  gatewayservices:
    image: ${ACR_LOGINSERVER-}gatewayservices
    build:
      context: .
      dockerfile: Gatewayservices\Dockerfile

